[build]
publish = "public"
command = "rm -rf themes/airspace-hugo && git clone https://github.com/themefisher/airspace-hugo.git themes/airspace-hugo && hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[build.environment]
HUGO_VERSION = "0.157.0"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"